
import { Poppins } from 'next/font/google'
import './globals.css'
import Navbar from './components/layouts/Navbar'
import Footer from './components/layouts/Footer'

const poppin = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata = {
  title: process.env.TITLE,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppin.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
